name: Run Tests on Push
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  push:
    branches:
      - feature/github-test

# env:
  # http_proxy: http://proxy-dmz.intel.com:911/
  # https_proxy: http://proxy-dmz.intel.com:912/
  # no_proxy: intel.com

jobs:
  Build-UnitTest-Run-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Install atlassian sdk
        uses: rodrigo-nogues/github-action-install-atlassian-sdk@v1
      - name: Check out jira plugin repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Run unit test
        run: |
          atlas-unit-test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
